#!/bin/bash
die(){ echo "$1">&2; exit "${2-1}"; }
shopt -s globstar extglob || die "globstar/extglob option not supported by your bash." 2

for file in ./**/*.@(patch|patch1|diff); do
    echo Apply "$file"
    patch -Np1 -i "$file" || die "Failed to patch $file"
done
echo "Done"
