#!/bin/bash
boom(){ printf 'fatal:\t%b' "$1">&2; exit "${2-1}"; }
shopt -s globstar extglob ||
    boom "globstar/extglob option not supported by your bash ($BASH_VERSION).
\\tTry using bash 4.x." 2

for file in ./**/*.@(patch|patch1|diff); do
    printf "info:\\tApply $file"
    patch -Np1 -i "$file" ||
        boom "Failed to patch $file."
done
echo "Done"
